### PR TITLE
fix: explicitly call end to finish sending request

### LINKED ISSUE #101: (Possible) incorrect use of readable stream
https://github.com/scality/sproxydclient/blob/rel/6.2.5/lib/sproxyd.js#L191

Shouldn't this be
```js
stream.on('end', () => request.end());
```
?

### PR DESCRIPTION
**Pull request by rahulreddy**
fixes #101

### CODE REVIEW

**Comment by rahulreddy** [comment]
@ironman-machine try

**Comment by rahulreddy** [comment]
@ironman-machine try

File: lib/sproxyd.js [hunk 1]
```diff
@@ -187,9 +187,14 @@ class SproxydClient {
...
+            request.on('finish',
+                () => log.debug('finished sending PUT chunks to sproxyd', {
+                    component: 'sproxydclient',
+                    method: '_handleRequest',
+                    contentLength: size,
+                }));
             stream.pipe(request);
-            request.on('end', () => request.end);
-            log.debug('finished sending PUT chunks to sproxyd');
+            // request.end();
```
Comment (ploki) [inline lib/sproxyd.js]: should go away

Comment (rahulreddy) [inline lib/sproxyd.js]: I removed it and the code is updated. Please review again.

**Comment by rahulreddy** [comment]
@ironman-machine try

File: lib/sproxyd.js [hunk 2]
```diff
@@ -187,9 +187,21 @@ class SproxydClient {
...
             stream.pipe(request);
-            request.on('end', () => request.end);
-            log.debug('finished sending PUT chunks to sproxyd');
+            stream.on('error', err => {
+                log.error('error from readable stream', {
+                    error: err,
+                    method: '_handleRequest',
+                    component: 'sproxydclient',
+                });
+                request.end();
```
Comment (ploki) [inline lib/sproxyd.js]: does it have the effect on the writable stream of closing the underlying tcp/ip connection to the remote host? if not, the remote host will wait until timeout for the remaining data to reach 'content-length'. (not good for stuffs like http keep-alive)

Comment (rahulreddy) [inline lib/sproxyd.js]: Yes, `request.end()` should close the connection to remote host. If not for this change, then it would behave like you said "kees the connection open with the remote host closing the connection after timeout"

Comment (ploki) [inline lib/sproxyd.js]: 👍
