### PR TITLE
Logs: Add log info for requests

### LINKED ISSUE #70: sproxydclient does not log the sproxyd key in case of PUT failure
Below are the S3 logs for a put that failed because of sproxyd:

```
{"name":"S3","clientIP":"::ffff:127.0.0.1","url":"/bucket/hosts","httpMethod":"PUT","bucketName":"bucket","objectKey":"hosts","method":"routePUT","time":1464831507196,"req_id":"7be34e7076355e5a4731","level":"info","message":"received request","hostname":"storenode03","pid":25}
{"name":"SproxydClient","method":"PUT","value":"[data]","args":{"bucketName":"bucket","owner":"PCTHS8N39D4MYYEDTRM3GLGZRRMEMIYPOZVIIVAICQ7WAVJ1YIOI6PSBL4A1N4K3","namespace":"default"},"counter":0,"time":1464831507252,"req_id":"7be34e7076355e5a4731:6534d914da6f716af3a4","level":"info","message":"request","hostname":"storenode03","pid":25}
{"name":"SproxydClient","method":"PUT","value":"[data]","args":{"bucketName":"bucket","owner":"PCTHS8N39D4MYYEDTRM3GLGZRRMEMIYPOZVIIVAICQ7WAVJ1YIOI6PSBL4A1N4K3","namespace":"default"},"counter":0,"time":1464831507252,"req_id":"7be34e7076355e5a4731:6534d914da6f716af3a4","level":"info","message":"request","hostname":"storenode03","pid":25}
{"name":"SproxydClient","time":1464831507259,"req_id":"7be34e7076355e5a4731:6534d914da6f716af3a4","level":"debug","message":"finished sending PUT chunks to sproxyd","hostname":"storenode03","pid":25}
{"name":"SproxydClient","statusCode":400,"time":1464831507264,"req_id":"7be34e7076355e5a4731:6534d914da6f716af3a4","level":"debug","message":"got expected response code:","hostname":"storenode03","pid":25}
{"name":"SproxydClient","msg":"400","time":1464831507264,"req_id":"7be34e7076355e5a4731:6534d914da6f716af3a4","level":"error","message":"PUT chunk to sproxyd","hostname":"storenode03","pid":25}
{"name":"SproxydClient","err":{"isExpected":true},"time":1464831507266,"req_id":"7be34e7076355e5a4731:6534d914da6f716af3a4","elapsed_ms":13.860506,"level":"info","message":"request received response","hostname":"storenode03","pid":25}
{"name":"S3","clientIP":"::ffff:127.0.0.1","url":"/bucket/hosts","httpMethod":"PUT","bucketName":"bucket","objectKey":"hosts","accessKey":"E29IGGCPXR92I3R0QXU9","time":1464831507190,"req_id":"7be34e7076355e5a4731","level":"debug","message":"routing request","hostname":"storenode03","pid":25}
{"name":"S3","clientIP":"::ffff:127.0.0.1","url":"/bucket/hosts","httpMethod":"PUT","bucketName":"bucket","objectKey":"hosts","accessKey":"E29IGGCPXR92I3R0QXU9","method":"routePUT","time":1464831507196,"req_id":"7be34e7076355e5a4731","level":"info","message":"received request","hostname":"storenode03","pid":25}
{"name":"S3","clientIP":"::ffff:127.0.0.1","url":"/bucket/hosts","httpMethod":"PUT","bucketName":"bucket","objectKey":"hosts","accessKey":"E29IGGCPXR92I3R0QXU9","method":"auth","time":1464831507198,"req_id":"7be34e7076355e5a4731","level":"debug","message":"running auth checks","hostname":"storenode03","pid":25}
{"name":"S3","clientIP":"::ffff:127.0.0.1","url":"/bucket/hosts","httpMethod":"PUT","bucketName":"bucket","objectKey":"hosts","accessKey":"E29IGGCPXR92I3R0QXU9","authHeader":"AWS E29IGGCPXR92I3R0QXU9:YMKQBhzPcSzGbfemQZgvPKvnlYw=","time":1464831507198,"req_id":"7be34e7076355e5a4731","level":"trace","message":"authorization header","hostname":"storenode03","pid":25}
{"name":"S3","clientIP":"::ffff:127.0.0.1","url":"/bucket/hosts","httpMethod":"PUT","bucketName":"bucket","objectKey":"hosts","accessKey":"E29IGGCPXR92I3R0QXU9","time":1464831507199,"req_id":"7be34e7076355e5a4731","level":"trace","message":"authenticating request with auth v2 using headers","hostname":"storenode03","pid":25}
{"name":"S3","clientIP":"::ffff:127.0.0.1","url":"/bucket/hosts","httpMethod":"PUT","bucketName":"bucket","objectKey":"hosts","accessKey":"E29IGGCPXR92I3R0QXU9","time":1464831507199,"req_id":"7be34e7076355e5a4731","level":"trace","message":"running header auth check","hostname":"storenode03","pid":25}
{"name":"S3","clientIP":"::ffff:127.0.0.1","url":"/bucket/hosts","httpMethod":"PUT","bucketName":"bucket","objectKey":"hosts","accessKey":"E29IGGCPXR92I3R0QXU9","requestTimestamp":1464831507000,"time":1464831507200,"req_id":"7be34e7076355e5a4731","level":"trace","message":"request timestamp","hostname":"storenode03","pid":25}
{"name":"S3","clientIP":"::ffff:127.0.0.1","url":"/bucket/hosts","httpMethod":"PUT","bucketName":"bucket","objectKey":"hosts","accessKey":"E29IGGCPXR92I3R0QXU9","currentTimestamp":1464831507200,"time":1464831507200,"req_id":"7be34e7076355e5a4731","level":"trace","message":"current timestamp","hostname":"storenode03","pid":25}
{"name":"S3","clientIP":"::ffff:127.0.0.1","url":"/bucket/hosts","httpMethod":"PUT","bucketName":"bucket","objectKey":"hosts","accessKey":"E29IGGCPXR92I3R0QXU9","signatureFromRequest":"YMKQBhzPcSzGbfemQZgvPKvnlYw=","time":1464831507201,"req_id":"7be34e7076355e5a4731","level":"trace","message":"signature from request","hostname":"storenode03","pid":25}
{"name":"S3","clientIP":"::ffff:127.0.0.1","url":"/bucket/hosts","httpMethod":"PUT","bucketName":"bucket","objectKey":"hosts","accessKey":"E29IGGCPXR92I3R0QXU9","time":1464831507201,"req_id":"7be34e7076355e5a4731","level":"trace","message":"constructing string to sign","hostname":"storenode03","pid":25}
{"name":"S3","clientIP":"::ffff:127.0.0.1","url":"/bucket/hosts","httpMethod":"PUT","bucketName":"bucket","objectKey":"hosts","accessKey":"E29IGGCPXR92I3R0QXU9","stringToSign":"PUT\n\ntext/plain\n\nx-amz-date:Thu, 02 Jun 2016 01:38:27 +0000\nx-amz-meta-s3cmd-attrs:uid:0/gname:root/uname:root/gid:0/mode:33188/mtime:1370615492/atime:1464754861/md5:54fb6627dbaa37721048e4549db3224d/ctime:1463605391\nx-amz-storage-class:STANDARD\n/bucket/hosts","time":1464831507203,"req_id":"7be34e7076355e5a4731","level":"trace","message":"constructed string to sign","hostname":"storenode03","pid":25}
{"name":"S3","clientIP":"::ffff:127.0.0.1","url":"/bucket/hosts","httpMethod":"PUT","bucketName":"bucket","objectKey":"hosts","accessKey":"E29IGGCPXR92I3R0QXU9","algo":"sha1","time":1464831507203,"req_id":"7be34e7076355e5a4731","level":"trace","message":"algo for calculating signature","hostname":"storenode03","pid":25}
{"name":"S3","clientIP":"::ffff:127.0.0.1","url":"/bucket/hosts","httpMethod":"PUT","bucketName":"bucket","objectKey":"hosts","accessKey":"E29IGGCPXR92I3R0QXU9","time":1464831507203,"req_id":"7be34e7076355e5a4731","level":"debug","message":"authenticating V2 request","hostname":"storenode03","pid":25}
{"name":"S3","clientIP":"::ffff:127.0.0.1","url":"/bucket/hosts","httpMethod":"PUT","bucketName":"bucket","objectKey":"hosts","accessKey":"E29IGGCPXR92I3R0QXU9","userInfo":{"message":{"code":200,"message":"Authentication successful","body":{"arn":"arn:aws:iam::520809164748:/Bart/","canonicalID":"PCTHS8N39D4MYYEDTRM3GLGZRRMEMIYPOZVIIVAICQ7WAVJ1YIOI6PSBL4A1N4K3","shortid":"FJRXIOAI7MOQQ2G6KESAYKEJMUP78ZT6","email":"none@somewhere.com","accountDisplayName":"accessKey1","IAMdisplayName":"Bart"}}},"time":1464831507230,"req_id":"7be34e7076355e5a4731","level":"debug","message":"received user info from Vault","hostname":"storenode03","pid":25}
{"name":"S3","clientIP":"::ffff:127.0.0.1","url":"/bucket/hosts","httpMethod":"PUT","bucketName":"bucket","objectKey":"hosts","accessKey":"E29IGGCPXR92I3R0QXU9","method":"objectPut","time":1464831507230,"req_id":"7be34e7076355e5a4731","level":"debug","message":"processing request","hostname":"storenode03","pid":25}
{"name":"S3","clientIP":"::ffff:127.0.0.1","url":"/bucket/hosts","httpMethod":"PUT","bucketName":"bucket","objectKey":"hosts","accessKey":"E29IGGCPXR92I3R0QXU9","canonicalID":"PCTHS8N39D4MYYEDTRM3GLGZRRMEMIYPOZVIIVAICQ7WAVJ1YIOI6PSBL4A1N4K3","time":1464831507231,"req_id":"7be34e7076355e5a4731","level":"trace","message":"owner canonicalID to send to data","hostname":"storenode03","pid":25}
{"name":"S3","clientIP":"::ffff:127.0.0.1","url":"/bucket/hosts","httpMethod":"PUT","bucketName":"bucket","objectKey":"hosts","accessKey":"E29IGGCPXR92I3R0QXU9","time":1464831507231,"req_id":"7be34e7076355e5a4731","level":"trace","message":"performing metadata validation checks","hostname":"storenode03","pid":25}
{"name":"S3","clientIP":"::ffff:127.0.0.1","url":"/bucket/hosts","httpMethod":"PUT","bucketName":"bucket","objectKey":"hosts","accessKey":"E29IGGCPXR92I3R0QXU9","database":"bucket","object":"hosts","time":1464831507231,"req_id":"7be34e7076355e5a4731","level":"debug","message":"getting bucket and object from metadata","hostname":"storenode03","pid":25}
{"name":"S3","clientIP":"::ffff:127.0.0.1","url":"/bucket/hosts","httpMethod":"PUT","bucketName":"bucket","objectKey":"hosts","accessKey":"E29IGGCPXR92I3R0QXU9","database":"bucket","object":"hosts","time":1464831507248,"req_id":"7be34e7076355e5a4731","level":"debug","message":"bucket and object retrieved from metadata","hostname":"storenode03","pid":25}
{"name":"S3","clientIP":"::ffff:127.0.0.1","url":"/bucket/hosts","httpMethod":"PUT","bucketName":"bucket","objectKey":"hosts","accessKey":"E29IGGCPXR92I3R0QXU9","time":1464831507249,"req_id":"7be34e7076355e5a4731","level":"trace","message":"found bucket and object in metadata","hostname":"storenode03","pid":25}
{"name":"S3","clientIP":"::ffff:127.0.0.1","url":"/bucket/hosts","httpMethod":"PUT","bucketName":"bucket","objectKey":"hosts","accessKey":"E29IGGCPXR92I3R0QXU9","metaHeaders":{"x-amz-meta-s3cmd-attrs":"uid:0/gname:root/uname:root/gid:0/mode:33188/mtime:1370615492/atime:1464754861/md5:54fb6627dbaa37721048e4549db3224d/ctime:1463605391"},"time":1464831507250,"req_id":"7be34e7076355e5a4731","level":"trace","message":"meta headers","hostname":"storenode03","pid":25}
{"name":"S3","clientIP":"::ffff:127.0.0.1","url":"/bucket/hosts","httpMethod":"PUT","bucketName":"bucket","objectKey":"hosts","accessKey":"E29IGGCPXR92I3R0QXU9","time":1464831507250,"req_id":"7be34e7076355e5a4731","level":"trace","message":"storing object in data","hostname":"storenode03","pid":25}
{"name":"S3","clientIP":"::ffff:127.0.0.1","url":"/bucket/hosts","httpMethod":"PUT","bucketName":"bucket","objectKey":"hosts","accessKey":"E29IGGCPXR92I3R0QXU9","implName":"sproxyd","keyContext":{"bucketName":"bucket","owner":"PCTHS8N39D4MYYEDTRM3GLGZRRMEMIYPOZVIIVAICQ7WAVJ1YIOI6PSBL4A1N4K3","namespace":"default"},"method":"put","time":1464831507251,"req_id":"7be34e7076355e5a4731","level":"debug","message":"sending put to datastore","hostname":"storenode03","pid":25}
{"name":"S3","clientIP":"::ffff:127.0.0.1","url":"/bucket/hosts","httpMethod":"PUT","bucketName":"bucket","objectKey":"hosts","accessKey":"E29IGGCPXR92I3R0QXU9","error":{"isExpected":true},"time":1464831507267,"req_id":"7be34e7076355e5a4731","level":"error","message":"error from sproxyd","hostname":"storenode03","pid":25}
{"name":"S3","clientIP":"::ffff:127.0.0.1","url":"/bucket/hosts","httpMethod":"PUT","bucketName":"bucket","objectKey":"hosts","accessKey":"E29IGGCPXR92I3R0QXU9","error":{"code":500,"description":"We encountered an internal error. Please try again.","InternalError":true},"time":1464831507270,"req_id":"7be34e7076355e5a4731","level":"error","message":"error in datastore","hostname":"storenode03","pid":25}
{"name":"S3","clientIP":"::ffff:127.0.0.1","url":"/bucket/hosts","httpMethod":"PUT","bucketName":"bucket","objectKey":"hosts","accessKey":"E29IGGCPXR92I3R0QXU9","error":{"code":500,"description":"We encountered an internal error. Please try again.","InternalError":true},"method":"services.dataStore","time":1464831507271,"req_id":"7be34e7076355e5a4731","level":"warn","message":"error from data","hostname":"storenode03","pid":25}
{"name":"S3","clientIP":"::ffff:127.0.0.1","url":"/bucket/hosts","httpMethod":"PUT","bucketName":"bucket","objectKey":"hosts","accessKey":"E29IGGCPXR92I3R0QXU9","clientIp":"::ffff:127.0.0.1","clientPort":39170,"httpURL":"/bucket/hosts","httpCode":500,"time":1464831507275,"req_id":"7be34e7076355e5a4731","elapsed_ms":85.805455,"level":"info","message":"responded with error XML","hostname":"storenode03","pid":25}
```

Here is the corresponding nginx/tengine log for that put:

```
{ "time":"2016-06-02T01:38:27+00:00","connection":"23","request":"1","hrtime":"1464831507.263","httpMethod":"PUT","url":"/arc2/B2E6D9A8D834B54FC2A8C034BFD01759F3851370","elapsed_ms":0,"httpCode":400,"requestLength":432,"bytesSent":333,"contentLength":"158","sentContentLength":"181","contentType":"application/octet-stream","s3Address":"10.10.2.3","requestUserMd":"-","responseUserMd":"-","ringKeyVersion":"-","ringStatus":"-","s3Port":"60060","sproxydStatus":"400","req_id":"7be34e7076355e5a4731:6534d914da6f716af3a4","ifMatch":"-","ifNoneMatch":"-","range":"-","contentRange":"-","nginxPID":12698,"sproxydAddress":"127.0.0.1:20001","sproxydResponseTime_s":"0.000" }
```

**===> From the above the sproxyd key is not logged on a failed put.**

### LINKED ISSUE #96: sproxydclient error and ring key
here is a failed sproxydclient transaction:

```
[root@asvppdxobjs301 logs]# grep d584f478164de6580ff2 repd-7.log
{"name":"Backup","index":3,"id":"10.128.50.105:9049/10.128.50.106:9049/10.128.50.107:9049/10.64.50.105:9049/10.64.50.106:9049","time":1483804801086,"req_id":"d584f478164de6580ff2","level":"info","message":"sending backup to datastore","hostname":"asvppdxobjs301.gecis.io","pid":91}
{"name":"Backup","key":"383AFE0000000000000003736486775AE9000070","time":1483804803405,"req_id":"d584f478164de6580ff2","level":"info","message":"sending backup to datastore","hostname":"asvppdxobjs301.gecis.io","pid":91}
{"name":"Backup","implName":"sproxyd","keyContext":"383AFE0000000000000003736486775AE9000070","method":"put","time":1483804803406,"req_id":"d584f478164de6580ff2","level":"info","message":"Putting backup to datastore","hostname":"asvppdxobjs301.gecis.io","pid":91}
{"name":"SproxydClient","method":"PUT","value":"383AFE0000000000000003736486775AE9000070","args":{"headers":{"content-length":44889619,"x-scal-usermd":"eyJjaGVja3N1bSI6ImUwZjRjNzNhYzJhNjQ5ODYyZDM3MDNlZDJlZTcyZDdhIiwiaW5kZXgiOjMsInNpemUiOjEwMDAwfQ=="}},"counter":0,"time":1483804803406,"req_id":"d584f478164de6580ff2:63432bc33b1946c82a32","level":"info","message":"request","hostname":"asvppdxobjs301.gecis.io","pid":91}
{"name":"SproxydClient","method":"PUT","value":"383AFE0000000000000003736486775AE9000070","args":{"headers":{"content-length":44889619,"x-scal-usermd":"eyJjaGVja3N1bSI6ImUwZjRjNzNhYzJhNjQ5ODYyZDM3MDNlZDJlZTcyZDdhIiwiaW5kZXgiOjMsInNpemUiOjEwMDAwfQ==","X-Scal-Replica-Policy":"immutable","content-type":"application/octet-stream","X-Scal-Request-Uids":"d584f478164de6580ff2:63432bc33b1946c82a32"}},"counter":0,"time":1483804803406,"req_id":"d584f478164de6580ff2:63432bc33b1946c82a32","level":"info","message":"request","hostname":"asvppdxobjs301.gecis.io","pid":91}
{"name":"SproxydClient","time":1483804803413,"req_id":"d584f478164de6580ff2:63432bc33b1946c82a32","level":"debug","message":"finished sending PUT chunks to sproxyd","hostname":"asvppdxobjs301.gecis.io","pid":91}
{"name":"SproxydClient","error":{"code":"ECONNRESET"},"time":1483804953437,"req_id":"d584f478164de6580ff2:63432bc33b1946c82a32","level":"error","message":"PUT chunk to sproxyd","hostname":"asvppdxobjs301.gecis.io","pid":91}
{"name":"SproxydClient","method":"PUT","value":"383AFE0000000000000003736486775AE9000070","args":{"headers":{"content-length":44889619,"x-scal-usermd":"eyJjaGVja3N1bSI6ImUwZjRjNzNhYzJhNjQ5ODYyZDM3MDNlZDJlZTcyZDdhIiwiaW5kZXgiOjMsInNpemUiOjEwMDAwfQ==","X-Scal-Replica-Policy":"immutable","content-type":"application/octet-stream","X-Scal-Request-Uids":"d584f478164de6580ff2:63432bc33b1946c82a32"}},"counter":1,"time":1483804953440,"req_id":"d584f478164de6580ff2:63432bc33b1946c82a32","level":"info","message":"request","hostname":"asvppdxobjs301.gecis.io","pid":91}
{"name":"SproxydClient","time":1483804953440,"req_id":"d584f478164de6580ff2:63432bc33b1946c82a32","level":"debug","message":"bootstrap head moved from 10.128.50.107,8181 to 10.64.50.105,8181","hostname":"asvppdxobjs301.gecis.io","pid":91}
{"name":"SproxydClient","method":"PUT","value":"383AFE0000000000000003736486775AE9000070","args":{"headers":{"content-length":44889619,"x-scal-usermd":"eyJjaGVja3N1bSI6ImUwZjRjNzNhYzJhNjQ5ODYyZDM3MDNlZDJlZTcyZDdhIiwiaW5kZXgiOjMsInNpemUiOjEwMDAwfQ==","X-Scal-Replica-Policy":"immutable","content-type":"application/octet-stream","X-Scal-Request-Uids":"d584f478164de6580ff2:63432bc33b1946c82a32"}},"counter":1,"time":1483804953440,"req_id":"d584f478164de6580ff2:63432bc33b1946c82a32","level":"info","message":"request","hostname":"asvppdxobjs301.gecis.io","pid":91}
{"name":"SproxydClient","time":1483804953446,"req_id":"d584f478164de6580ff2:63432bc33b1946c82a32","level":"debug","message":"finished sending PUT chunks to sproxyd","hostname":"asvppdxobjs301.gecis.io","pid":91}
{"name":"SproxydClient","error":{"code":"ECONNRESET"},"time":1483805103550,"req_id":"d584f478164de6580ff2:63432bc33b1946c82a32","level":"error","message":"PUT chunk to sproxyd","hostname":"asvppdxobjs301.gecis.io","pid":91}
{"name":"SproxydClient","method":"PUT","value":"383AFE0000000000000003736486775AE9000070","args":{"headers":{"content-length":44889619,"x-scal-usermd":"eyJjaGVja3N1bSI6ImUwZjRjNzNhYzJhNjQ5ODYyZDM3MDNlZDJlZTcyZDdhIiwiaW5kZXgiOjMsInNpemUiOjEwMDAwfQ==","X-Scal-Replica-Policy":"immutable","content-type":"application/octet-stream","X-Scal-Request-Uids":"d584f478164de6580ff2:63432bc33b1946c82a32"}},"counter":2,"time":1483805103550,"req_id":"d584f478164de6580ff2:63432bc33b1946c82a32","level":"info","message":"request","hostname":"asvppdxobjs301.gecis.io","pid":91}
{"name":"SproxydClient","time":1483805103550,"req_id":"d584f478164de6580ff2:63432bc33b1946c82a32","level":"debug","message":"bootstrap head moved from 10.64.50.105,8181 to 10.128.50.108,8181","hostname":"asvppdxobjs301.gecis.io","pid":91}
{"name":"SproxydClient","method":"PUT","value":"383AFE0000000000000003736486775AE9000070","args":{"headers":{"content-length":44889619,"x-scal-usermd":"eyJjaGVja3N1bSI6ImUwZjRjNzNhYzJhNjQ5ODYyZDM3MDNlZDJlZTcyZDdhIiwiaW5kZXgiOjMsInNpemUiOjEwMDAwfQ==","X-Scal-Replica-Policy":"immutable","content-type":"application/octet-stream","X-Scal-Request-Uids":"d584f478164de6580ff2:63432bc33b1946c82a32"}},"counter":2,"time":1483805103550,"req_id":"d584f478164de6580ff2:63432bc33b1946c82a32","level":"info","message":"request","hostname":"asvppdxobjs301.gecis.io","pid":91}
{"name":"SproxydClient","time":1483805103552,"req_id":"d584f478164de6580ff2:63432bc33b1946c82a32","level":"debug","message":"finished sending PUT chunks to sproxyd","hostname":"asvppdxobjs301.gecis.io","pid":91}
{"name":"SproxydClient","error":{"code":"ECONNRESET"},"time":1483805253631,"req_id":"d584f478164de6580ff2:63432bc33b1946c82a32","level":"error","message":"PUT chunk to sproxyd","hostname":"asvppdxobjs301.gecis.io","pid":91}
{"name":"SproxydClient","method":"PUT","value":"383AFE0000000000000003736486775AE9000070","args":{"headers":{"content-length":44889619,"x-scal-usermd":"eyJjaGVja3N1bSI6ImUwZjRjNzNhYzJhNjQ5ODYyZDM3MDNlZDJlZTcyZDdhIiwiaW5kZXgiOjMsInNpemUiOjEwMDAwfQ==","X-Scal-Replica-Policy":"immutable","content-type":"application/octet-stream","X-Scal-Request-Uids":"d584f478164de6580ff2:63432bc33b1946c82a32"}},"counter":3,"time":1483805253632,"req_id":"d584f478164de6580ff2:63432bc33b1946c82a32","level":"info","message":"request","hostname":"asvppdxobjs301.gecis.io","pid":91}
{"name":"SproxydClient","time":1483805253632,"req_id":"d584f478164de6580ff2:63432bc33b1946c82a32","level":"debug","message":"bootstrap head moved from 10.128.50.108,8181 to 10.64.50.108,8181","hostname":"asvppdxobjs301.gecis.io","pid":91}
{"name":"SproxydClient","method":"PUT","value":"383AFE0000000000000003736486775AE9000070","args":{"headers":{"content-length":44889619,"x-scal-usermd":"eyJjaGVja3N1bSI6ImUwZjRjNzNhYzJhNjQ5ODYyZDM3MDNlZDJlZTcyZDdhIiwiaW5kZXgiOjMsInNpemUiOjEwMDAwfQ==","X-Scal-Replica-Policy":"immutable","content-type":"application/octet-stream","X-Scal-Request-Uids":"d584f478164de6580ff2:63432bc33b1946c82a32"}},"counter":3,"time":1483805253632,"req_id":"d584f478164de6580ff2:63432bc33b1946c82a32","level":"info","message":"request","hostname":"asvppdxobjs301.gecis.io","pid":91}
{"name":"SproxydClient","time":1483805253633,"req_id":"d584f478164de6580ff2:63432bc33b1946c82a32","level":"debug","message":"finished sending PUT chunks to sproxyd","hostname":"asvppdxobjs301.gecis.io","pid":91}
{"name":"SproxydClient","error":{"code":"ECONNRESET"},"time":1483805403694,"req_id":"d584f478164de6580ff2:63432bc33b1946c82a32","level":"error","message":"PUT chunk to sproxyd","hostname":"asvppdxobjs301.gecis.io","pid":91}
{"name":"SproxydClient","method":"PUT","value":"383AFE0000000000000003736486775AE9000070","args":{"headers":{"content-length":44889619,"x-scal-usermd":"eyJjaGVja3N1bSI6ImUwZjRjNzNhYzJhNjQ5ODYyZDM3MDNlZDJlZTcyZDdhIiwiaW5kZXgiOjMsInNpemUiOjEwMDAwfQ==","X-Scal-Replica-Policy":"immutable","content-type":"application/octet-stream","X-Scal-Request-Uids":"d584f478164de6580ff2:63432bc33b1946c82a32"}},"counter":4,"time":1483805403697,"req_id":"d584f478164de6580ff2:63432bc33b1946c82a32","level":"info","message":"request","hostname":"asvppdxobjs301.gecis.io","pid":91}
{"name":"SproxydClient","time":1483805403697,"req_id":"d584f478164de6580ff2:63432bc33b1946c82a32","level":"debug","message":"bootstrap head moved from 10.64.50.108,8181 to 10.128.50.106,8181","hostname":"asvppdxobjs301.gecis.io","pid":91}
{"name":"SproxydClient","method":"PUT","value":"383AFE0000000000000003736486775AE9000070","args":{"headers":{"content-length":44889619,"x-scal-usermd":"eyJjaGVja3N1bSI6ImUwZjRjNzNhYzJhNjQ5ODYyZDM3MDNlZDJlZTcyZDdhIiwiaW5kZXgiOjMsInNpemUiOjEwMDAwfQ==","X-Scal-Replica-Policy":"immutable","content-type":"application/octet-stream","X-Scal-Request-Uids":"d584f478164de6580ff2:63432bc33b1946c82a32"}},"counter":4,"time":1483805403697,"req_id":"d584f478164de6580ff2:63432bc33b1946c82a32","level":"info","message":"request","hostname":"asvppdxobjs301.gecis.io","pid":91}
{"name":"SproxydClient","time":1483805403701,"req_id":"d584f478164de6580ff2:63432bc33b1946c82a32","level":"debug","message":"finished sending PUT chunks to sproxyd","hostname":"asvppdxobjs301.gecis.io","pid":91}
{"name":"SproxydClient","error":{"code":"ECONNRESET"},"time":1483805553742,"req_id":"d584f478164de6580ff2:63432bc33b1946c82a32","level":"error","message":"PUT chunk to sproxyd","hostname":"asvppdxobjs301.gecis.io","pid":91}
{"name":"SproxydClient","method":"PUT","value":"383AFE0000000000000003736486775AE9000070","args":{"headers":{"content-length":44889619,"x-scal-usermd":"eyJjaGVja3N1bSI6ImUwZjRjNzNhYzJhNjQ5ODYyZDM3MDNlZDJlZTcyZDdhIiwiaW5kZXgiOjMsInNpemUiOjEwMDAwfQ==","X-Scal-Replica-Policy":"immutable","content-type":"application/octet-stream","X-Scal-Request-Uids":"d584f478164de6580ff2:63432bc33b1946c82a32"}},"counter":5,"time":1483805553744,"req_id":"d584f478164de6580ff2:63432bc33b1946c82a32","level":"info","message":"request","hostname":"asvppdxobjs301.gecis.io","pid":91}
{"name":"SproxydClient","time":1483805553743,"req_id":"d584f478164de6580ff2:63432bc33b1946c82a32","level":"debug","message":"bootstrap head moved from 10.128.50.106,8181 to 10.64.50.109,8181","hostname":"asvppdxobjs301.gecis.io","pid":91}
{"name":"SproxydClient","method":"PUT","value":"383AFE0000000000000003736486775AE9000070","args":{"headers":{"content-length":44889619,"x-scal-usermd":"eyJjaGVja3N1bSI6ImUwZjRjNzNhYzJhNjQ5ODYyZDM3MDNlZDJlZTcyZDdhIiwiaW5kZXgiOjMsInNpemUiOjEwMDAwfQ==","X-Scal-Replica-Policy":"immutable","content-type":"application/octet-stream","X-Scal-Request-Uids":"d584f478164de6580ff2:63432bc33b1946c82a32"}},"counter":5,"time":1483805553744,"req_id":"d584f478164de6580ff2:63432bc33b1946c82a32","level":"info","message":"request","hostname":"asvppdxobjs301.gecis.io","pid":91}
{"name":"SproxydClient","time":1483805553746,"req_id":"d584f478164de6580ff2:63432bc33b1946c82a32","level":"debug","message":"finished sending PUT chunks to sproxyd","hostname":"asvppdxobjs301.gecis.io","pid":91}
{"name":"SproxydClient","error":{"code":"ECONNRESET"},"time":1483805703827,"req_id":"d584f478164de6580ff2:63432bc33b1946c82a32","level":"error","message":"PUT chunk to sproxyd","hostname":"asvppdxobjs301.gecis.io","pid":91}
{"name":"SproxydClient","method":"PUT","value":"383AFE0000000000000003736486775AE9000070","args":{"headers":{"content-length":44889619,"x-scal-usermd":"eyJjaGVja3N1bSI6ImUwZjRjNzNhYzJhNjQ5ODYyZDM3MDNlZDJlZTcyZDdhIiwiaW5kZXgiOjMsInNpemUiOjEwMDAwfQ==","X-Scal-Replica-Policy":"immutable","content-type":"application/octet-stream","X-Scal-Request-Uids":"d584f478164de6580ff2:63432bc33b1946c82a32"}},"counter":6,"time":1483805703828,"req_id":"d584f478164de6580ff2:63432bc33b1946c82a32","level":"info","message":"request","hostname":"asvppdxobjs301.gecis.io","pid":91}
{"name":"SproxydClient","time":1483805703828,"req_id":"d584f478164de6580ff2:63432bc33b1946c82a32","level":"debug","message":"bootstrap head moved from 10.64.50.109,8181 to 10.64.50.106,8181","hostname":"asvppdxobjs301.gecis.io","pid":91}
{"name":"SproxydClient","method":"PUT","value":"383AFE0000000000000003736486775AE9000070","args":{"headers":{"content-length":44889619,"x-scal-usermd":"eyJjaGVja3N1bSI6ImUwZjRjNzNhYzJhNjQ5ODYyZDM3MDNlZDJlZTcyZDdhIiwiaW5kZXgiOjMsInNpemUiOjEwMDAwfQ==","X-Scal-Replica-Policy":"immutable","content-type":"application/octet-stream","X-Scal-Request-Uids":"d584f478164de6580ff2:63432bc33b1946c82a32"}},"counter":6,"time":1483805703828,"req_id":"d584f478164de6580ff2:63432bc33b1946c82a32","level":"info","message":"request","hostname":"asvppdxobjs301.gecis.io","pid":91}
{"name":"SproxydClient","time":1483805703829,"req_id":"d584f478164de6580ff2:63432bc33b1946c82a32","level":"debug","message":"finished sending PUT chunks to sproxyd","hostname":"asvppdxobjs301.gecis.io","pid":91}
{"name":"SproxydClient","error":{"code":"ECONNRESET"},"time":1483805853860,"req_id":"d584f478164de6580ff2:63432bc33b1946c82a32","level":"error","message":"PUT chunk to sproxyd","hostname":"asvppdxobjs301.gecis.io","pid":91}
{"name":"SproxydClient","method":"PUT","value":"383AFE0000000000000003736486775AE9000070","args":{"headers":{"content-length":44889619,"x-scal-usermd":"eyJjaGVja3N1bSI6ImUwZjRjNzNhYzJhNjQ5ODYyZDM3MDNlZDJlZTcyZDdhIiwiaW5kZXgiOjMsInNpemUiOjEwMDAwfQ==","X-Scal-Replica-Policy":"immutable","content-type":"application/octet-stream","X-Scal-Request-Uids":"d584f478164de6580ff2:63432bc33b1946c82a32"}},"counter":7,"time":1483805853868,"req_id":"d584f478164de6580ff2:63432bc33b1946c82a32","level":"info","message":"request","hostname":"asvppdxobjs301.gecis.io","pid":91}
{"name":"SproxydClient","time":1483805853867,"req_id":"d584f478164de6580ff2:63432bc33b1946c82a32","level":"debug","message":"bootstrap head moved from 10.64.50.106,8181 to 10.128.50.109,8181","hostname":"asvppdxobjs301.gecis.io","pid":91}
{"name":"SproxydClient","method":"PUT","value":"383AFE0000000000000003736486775AE9000070","args":{"headers":{"content-length":44889619,"x-scal-usermd":"eyJjaGVja3N1bSI6ImUwZjRjNzNhYzJhNjQ5ODYyZDM3MDNlZDJlZTcyZDdhIiwiaW5kZXgiOjMsInNpemUiOjEwMDAwfQ==","X-Scal-Replica-Policy":"immutable","content-type":"application/octet-stream","X-Scal-Request-Uids":"d584f478164de6580ff2:63432bc33b1946c82a32"}},"counter":7,"time":1483805853868,"req_id":"d584f478164de6580ff2:63432bc33b1946c82a32","level":"info","message":"request","hostname":"asvppdxobjs301.gecis.io","pid":91}
{"name":"SproxydClient","time":1483805853881,"req_id":"d584f478164de6580ff2:63432bc33b1946c82a32","level":"debug","message":"finished sending PUT chunks to sproxyd","hostname":"asvppdxobjs301.gecis.io","pid":91}
{"name":"SproxydClient","error":{"code":"ECONNRESET"},"time":1483806003893,"req_id":"d584f478164de6580ff2:63432bc33b1946c82a32","level":"error","message":"PUT chunk to sproxyd","hostname":"asvppdxobjs301.gecis.io","pid":91}
{"name":"SproxydClient","method":"PUT","value":"383AFE0000000000000003736486775AE9000070","args":{"headers":{"content-length":44889619,"x-scal-usermd":"eyJjaGVja3N1bSI6ImUwZjRjNzNhYzJhNjQ5ODYyZDM3MDNlZDJlZTcyZDdhIiwiaW5kZXgiOjMsInNpemUiOjEwMDAwfQ==","X-Scal-Replica-Policy":"immutable","content-type":"application/octet-stream","X-Scal-Request-Uids":"d584f478164de6580ff2:63432bc33b1946c82a32"}},"counter":8,"time":1483806003893,"req_id":"d584f478164de6580ff2:63432bc33b1946c82a32","level":"info","message":"request","hostname":"asvppdxobjs301.gecis.io","pid":91}
{"name":"SproxydClient","time":1483806003893,"req_id":"d584f478164de6580ff2:63432bc33b1946c82a32","level":"debug","message":"bootstrap head moved from 10.128.50.109,8181 to 10.64.50.107,8181","hostname":"asvppdxobjs301.gecis.io","pid":91}
{"name":"SproxydClient","method":"PUT","value":"383AFE0000000000000003736486775AE9000070","args":{"headers":{"content-length":44889619,"x-scal-usermd":"eyJjaGVja3N1bSI6ImUwZjRjNzNhYzJhNjQ5ODYyZDM3MDNlZDJlZTcyZDdhIiwiaW5kZXgiOjMsInNpemUiOjEwMDAwfQ==","X-Scal-Replica-Policy":"immutable","content-type":"application/octet-stream","X-Scal-Request-Uids":"d584f478164de6580ff2:63432bc33b1946c82a32"}},"counter":8,"time":1483806003893,"req_id":"d584f478164de6580ff2:63432bc33b1946c82a32","level":"info","message":"request","hostname":"asvppdxobjs301.gecis.io","pid":91}
{"name":"SproxydClient","time":1483806003894,"req_id":"d584f478164de6580ff2:63432bc33b1946c82a32","level":"debug","message":"finished sending PUT chunks to sproxyd","hostname":"asvppdxobjs301.gecis.io","pid":91}
{"name":"SproxydClient","error":{"code":"ECONNRESET"},"time":1483806153989,"req_id":"d584f478164de6580ff2:63432bc33b1946c82a32","level":"error","message":"PUT chunk to sproxyd","hostname":"asvppdxobjs301.gecis.io","pid":91}
{"name":"SproxydClient","method":"PUT","value":"383AFE0000000000000003736486775AE9000070","args":{"headers":{"content-length":44889619,"x-scal-usermd":"eyJjaGVja3N1bSI6ImUwZjRjNzNhYzJhNjQ5ODYyZDM3MDNlZDJlZTcyZDdhIiwiaW5kZXgiOjMsInNpemUiOjEwMDAwfQ==","X-Scal-Replica-Policy":"immutable","content-type":"application/octet-stream","X-Scal-Request-Uids":"d584f478164de6580ff2:63432bc33b1946c82a32"}},"counter":9,"time":1483806153990,"req_id":"d584f478164de6580ff2:63432bc33b1946c82a32","level":"info","message":"request","hostname":"asvppdxobjs301.gecis.io","pid":91}
{"name":"SproxydClient","time":1483806153990,"req_id":"d584f478164de6580ff2:63432bc33b1946c82a32","level":"debug","message":"bootstrap head moved from 10.64.50.107,8181 to 10.128.50.105,8181","hostname":"asvppdxobjs301.gecis.io","pid":91}
{"name":"SproxydClient","method":"PUT","value":"383AFE0000000000000003736486775AE9000070","args":{"headers":{"content-length":44889619,"x-scal-usermd":"eyJjaGVja3N1bSI6ImUwZjRjNzNhYzJhNjQ5ODYyZDM3MDNlZDJlZTcyZDdhIiwiaW5kZXgiOjMsInNpemUiOjEwMDAwfQ==","X-Scal-Replica-Policy":"immutable","content-type":"application/octet-stream","X-Scal-Request-Uids":"d584f478164de6580ff2:63432bc33b1946c82a32"}},"counter":9,"time":1483806153990,"req_id":"d584f478164de6580ff2:63432bc33b1946c82a32","level":"info","message":"request","hostname":"asvppdxobjs301.gecis.io","pid":91}
{"name":"SproxydClient","time":1483806153992,"req_id":"d584f478164de6580ff2:63432bc33b1946c82a32","level":"debug","message":"finished sending PUT chunks to sproxyd","hostname":"asvppdxobjs301.gecis.io","pid":91}
{"name":"SproxydClient","error":{"code":"ECONNRESET"},"time":1483806304077,"req_id":"d584f478164de6580ff2:63432bc33b1946c82a32","level":"error","message":"PUT chunk to sproxyd","hostname":"asvppdxobjs301.gecis.io","pid":91}
{"name":"SproxydClient","retries":10,"time":1483806304078,"req_id":"d584f478164de6580ff2:63432bc33b1946c82a32","elapsed_ms":1500672.426628,"level":"error","message":"failover tried too many times, giving up","hostname":"asvppdxobjs301.gecis.io","pid":91}
{"name":"Backup","index":3,"id":"10.128.50.105:9049/10.128.50.106:9049/10.128.50.107:9049/10.64.50.105:9049/10.64.50.106:9049","time":1483804801086,"req_id":"d584f478164de6580ff2","level":"info","message":"sending backup to datastore","hostname":"asvppdxobjs301.gecis.io","pid":91}
{"name":"Backup","key":"383AFE0000000000000003736486775AE9000070","time":1483804803405,"req_id":"d584f478164de6580ff2","level":"info","message":"sending backup to datastore","hostname":"asvppdxobjs301.gecis.io","pid":91}
{"name":"Backup","implName":"sproxyd","keyContext":"383AFE0000000000000003736486775AE9000070","method":"put","time":1483804803406,"req_id":"d584f478164de6580ff2","level":"info","message":"Putting backup to datastore","hostname":"asvppdxobjs301.gecis.io","pid":91}
{"name":"Backup","error":{"code":"ECONNRESET"},"time":1483806304079,"req_id":"d584f478164de6580ff2","level":"error","message":"error from sproxyd","hostname":"asvppdxobjs301.gecis.io","pid":91}
{"name":"SproxydClient","method":"HEAD","value":"383AFE0000000000000003736486775AE9000070","args":{},"counter":0,"time":1483806304081,"req_id":"d584f478164de6580ff2:21b5fb631fcf8a1bc25a","level":"info","message":"request","hostname":"asvppdxobjs301.gecis.io","pid":91}
{"name":"SproxydClient","error":{"code":404,"isExpected":true},"time":1483806304115,"req_id":"d584f478164de6580ff2:21b5fb631fcf8a1bc25a","elapsed_ms":33.816019,"level":"info","message":"request received response","hostname":"asvppdxobjs301.gecis.io","pid":91}
[root@asvppdxobjs301 logs]#
```

sproxydclient retries several times. This is good.  The error log line reporting the failure is:

```
{"name":"SproxydClient","error":{"code":"ECONNRESET"},"time":1483804953437,"req_id":"d584f478164de6580ff2:63432bc33b1946c82a32","level":"error","message":"PUT chunk to sproxyd","hostname":"asvppdxobjs301.gecis.io","pid":91}
```
It would ease analysis if:
 - the error log line contained the ip/port of the sproxyd involved in the transaction
- the error log line contained the ring key involved in the failure, not just the req_id

Ideally the same reasioning applies for non error behavior (one a single line, a successful sproxyd client should contain a req_id, a timestamp, the ring key, the status code, and the ip/port of the sproxyd involved in the transaction).

This is not a tooling problem. Doing things this way will help working on logs with kibana or with grep.

### PR DESCRIPTION
**Pull request by LaurenSpiegel**
Fixes #96 
Fixes #70

### CODE REVIEW

**Comment by LaurenSpiegel** [comment]
@ironman-machine go

**Comment by LaurenSpiegel** [comment]
@ironman-machine again

**Comment by LaurenSpiegel** [comment]
This is how a successful put looks:
{"name":"SproxydClient","method":"PUT","args":{"bucketName":"streambucket","owner":"001b6d5df7317aa50fa68b22fee91dd7c344f141cfe9e342ad836821fac46d1b","namespace":"default"},"counter":0,"time":1484107288918,"req_id":"ce54b82f36f5cdf2b91a:18e0f80910b5f003f7e2","level":"info","message":"request","hostname":"box47","pid":122}
{"name":"SproxydClient","host":["localhost","8181"],"key":"2D2A99DE7B92BE6EC2FA9D7CB84B7E5996929B20","statusCode":200,"time":1484107291084,"req_id":"ce54b82f36f5cdf2b91a:18e0f80910b5f003f7e2","level":"info","message":"stored to sproxyd","hostname":"box47","pid":122}

This is how a successful get looks:
{"name":"SproxydClient","method":"GET","key":"EA115B1A954DB0CAC2FA9D7CB84B7E5985000C20","args":{},"counter":0,"time":1484107287979,"req_id":"f8d4fa9f6ec60207e77c:2d21ab84d722ebcb0e69","level":"info","message":"request","hostname":"box47","pid":116}
{"name":"SproxydClient","host":["localhost","8181"],"statusCode":200,"key":"EA115B1A954DB0CAC2FA9D7CB84B7E5985000C20","time":1484107288005,"req_id":"f8d4fa9f6ec60207e77c:2d21ab84d722ebcb0e69","level":"info","message":"successful _handleRequest","hostname":"box47","pid":116}
{"name":"SproxydClient","error":null,"time":1484107288006,"req_id":"f8d4fa9f6ec60207e77c:2d21ab84d722ebcb0e69","elapsed_ms":26.176091,"level":"info","message":"request received response","hostname":"box47","pid":116}

@msegura, does this make all of your dreams come true?

File: lib/sproxyd.js [hunk 1]
```diff
@@ -147,9 +147,8 @@ class SproxydClient {
 
     _failover(method, stream, size, key, tries, log, callback, params) {
         const args = params === undefined ? {} : params;
-        const value = key || '[data]';
         let counter = tries;
-        log.info('request', { method, value, args, counter });
+        log.info('request', { method, key, args, counter });
```
Comment (rahulreddy) [inline lib/sproxyd.js]: While we are here we should update the log message to be more specific. Something like
`sending request to sproxyd`

File: lib/sproxyd.js [hunk 2]
```diff
@@ -176,23 +175,35 @@ class SproxydClient {
...
             });
             stream.pipe(request);
             request.on('end', () => request.end);
             log.debug('finished sending PUT chunks to sproxyd');
         } else {
             headers['content-length'] = 0;
-            const request = _createRequest(req, log, callback);
+            const request = _createRequest(req, log, (err, response) => {
+                if (err) {
+                    log.error('error in _handleRequest', { host,
```
Comment (rahulreddy) [inline lib/sproxyd.js]: This log message could be `error sending sproxyd request` and a method property as _handleRequest would be appropriate.

File: lib/sproxyd.js [hunk 3]
```diff
@@ -176,23 +175,35 @@ class SproxydClient {
...
+                        error: err, key: newKey });
+                    return callback(err);
+                }
+                log.debug('successful _handleRequest', { host,
```
Comment (rahulreddy) [inline lib/sproxyd.js]: Same here `success sending sproxyd request`
